(setq v1 (read))
(setq v2 (read))
(if (and (= v1 1) (= v2 1))
				 (write 1)
				 (write 0))
(terpri)
(if (and (= v1 0) (= v2 0))
				 (write 0)
				 (write 1))
(terpri)
(if (= v1 v2)
		(write 0)
		(write 1)
		)
