(setq kor (read))
(setq eng (read))
(setq mat (read))
(setq res (/ (+ kor eng mat) 3.0))
(format t "~,2f " res)
(if (> res 89)
		(write-string "A")
		(if (> res 79)
				(write-string "B")
				(if (> res 69)
						(write-string "C")
						(if (> res 59)
								(write-string "D")
								(write-string "F"))))
		)
